export const PERMISSION_FIELDS = [
  { name: 'xreport', label: 'X Report' },
  { name: 'zakazVirtual', label: 'Zakaz Virtual' },
  { name: 'stoplist', label: 'Stoplist' },
  { name: 'passwords', label: 'Passwords' },
  { name: 'notifications', label: 'Notifications' },
  { name: 'docs', label: 'Docs' },
  { name: 'stockReport', label: 'Stock Report' },
  { name: 'relazReport', label: 'Relaz Report' },
  { name: 'cashSummary', label: 'Cash Summary' },
  { name: 'cashbook', label: 'Cashbook' },
  { name: 'msettlements', label: 'M.Settlements' },
  { name: 'users', label: 'Users' },
  { name: 'category', label: 'Category' },
  { name: 'printers', label: 'Printers' },
  { name: 'reservation', label: 'Reservation' },
  { name: 'dynamicReports', label: 'Dyn. Reports' },
]

export const buildDefaults = (dbKey: string) => ({
  userId: null,
  dbKey,
  dbname: '',
  url: '',
  docUserId: null,
  reportIds: [],
  xreport: false,
  zakazVirtual: false,
  stoplist: false,
  passwords: false,
  notifications: false,
  docs: false,
  stockReport: false,
  relazReport: false,
  cashSummary: false,
  cashbook: false,
  msettlements: false,
  users: false,
  category: false,
  printers: false,
  reservation: false,
  dynamicReports: false,
})
