export const PERMISSION_FIELDS = [
  { name: 'xreport', label: 'отчет' },
  { name: 'zakazVirtual', label: 'открытые чеки' },
  { name: 'stoplist', label: 'стоп-лист' },
  { name: 'passwords', label: 'пароли' },
  { name: 'notifications', label: 'уведомления' },
  { name: 'docs', label: 'документы' },
  { name: 'stockReport', label: 'отчет по складу' },
  { name: 'relazReport', label: 'отчет по реализации' },
  { name: 'cashSummary', label: 'свод по кассе' },
  { name: 'cashbook', label: 'кассовая книга' },
  { name: 'msettlements', label: 'взаиморасчеты' },
  { name: 'users', label: 'пользователи' },
  { name: 'category', label: 'продукты' },
  { name: 'printers', label: 'принтеры' },
  { name: 'reservation', label: 'бронь' },
  { name: 'dynamicReports', label: 'динамические отчеты' },
]

export const PERMISSION_GROUPS = [
  {
    label: 'Основное',
    fields: ['xreport', 'zakazVirtual', 'stoplist', 'passwords', 'notifications', 'reservation'],
  },
  {
    label: 'Склад и касса',
    fields: [
      'docs',
      'stockReport',
      'relazReport',
      'cashSummary',
      'cashbook',
      'msettlements',
      'dynamicReports',
    ],
  },
  {
    label: 'Справочники',
    fields: ['users', 'category', 'printers'],
  },
] satisfies { label: string; fields: (keyof ReturnType<typeof buildDefaults>)[] }[]

export const buildDefaults = (dbKey: string) => ({
  userId: null,
  dbKey,
  dbname: '',
  url: '',
  docUserId: null,
  reportIds: [],
  xreport: false,
  zakazVirtual: false,
  stoplist: false,
  passwords: false,
  notifications: false,
  docs: false,
  stockReport: false,
  relazReport: false,
  cashSummary: false,
  cashbook: false,
  msettlements: false,
  users: false,
  category: false,
  printers: false,
  reservation: false,
  dynamicReports: false,
})
